#!/usr/bin/perl

# Some example invocations:
#
# ./split-MOD-into-channels --mod-path ~/Music/mp3s/Mods/yonqatan.mod --num=4 --out-prefix=./yonqatan-foo
#
# ./split-MOD-into-channels --mod-path ~/Music/mp3s/Mods/inside.s3m --num=8 --out-prefix=./inside-WAVs
#

use strict;
use warnings;

use autodie;

use Getopt::Long qw(GetOptions);

my $mod_path;
my $wav_path_prefix;
my $num_channels;

GetOptions(
    'num=i' => \$num_channels,
    'out-prefix=s' => \$wav_path_prefix,
    'mod-path=s' => \$mod_path,
) or die "Wrong options given. $!.";

if (!defined($mod_path))
{
    die "You must specify the module path using --mod-path.";
}

if (!defined($num_channels))
{
    die "You must specify the number of channels in the MOD using --num.";
}

if (!defined($wav_path_prefix))
{
    die "You must specify the prefix for the WAVs using --out-prefix.";
}

foreach my $chan_idx (0 .. $num_channels - 1)
{
    my @cmd = (
        "xmp", sprintf("-o%s-%04d.wav", $wav_path_prefix, $chan_idx),
        '--solo', $chan_idx,
        $mod_path,
    );

    if ( system(@cmd) )
    {
        die "Command failed for channel $chan_idx - $! . Command is << @cmd >>.";
    }
}

__END__

=head1 COPYRIGHT & LICENSE

Copyright 2014 by Shlomi Fish

This program is distributed under the MIT (X11) License:
L<http://www.opensource.org/licenses/mit-license.php>

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

=cut
